import Head from "next/head";
import Image from "next/image";
import Feature from "../Components/PageComponents/Home/Feature/Feature";
import Hero from "../Components/PageComponents/Home/Hero/Hero";
import Button from "../Components/UI/Button/Button";
import { Card } from "../Components/UI/Card/Card";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div >
      <Head>
        <title>Real Estate</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
    <Hero/>
<Feature/>
      
      </main>
    </div>
  );
}
